import Head from 'next/head';
import { Typography } from '@lib/common/typography';
import Button from '@lib/common/button';
import { XStack } from '@lib/common/stack';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Typography>sdfsdfsd</Typography>
        <XStack>
          <Button>primary button</Button>
        </XStack>
      </main>
    </div>
  );
}
