import Head from 'next/head';
import { Typography } from '@lib/common/typography';
import Button from '@lib/common/button';
import { XStack } from '@lib/common/stack';
import Container from '@lib/common/container';
import Box from '@lib/common/box';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <XStack wrap>
          <Box css={{ width: '25%', padding: '10px' }}>
            <Button variant="purple">primary button</Button>
          </Box>

          <Box css={{ width: '25%', padding: '10px' }}>
            <Button variant="purple">primary button</Button>
          </Box>

          <Box css={{ width: '25%', padding: '10px' }}>
            <Button variant="purple">primary button</Button>
          </Box>

          <Box css={{ width: '25%', padding: '10px' }}>
            <Button variant="purple">primary button</Button>
          </Box>

          <Box css={{ width: '25%', padding: '10px' }}>
            <Button variant="purple">primary button</Button>
          </Box>

          <Box css={{ width: '25%', padding: '10px' }}>
            <Button variant="purple">primary button</Button>
          </Box>
        </XStack>
      </Container>
    </div>
  );
}
